title: Search Yugioh Card | whdzera
email: whdzera@gmail.com
baseurl: "/search-yugioh-card" 
url: ""
twitter_username: whdzera
github_username:  rokhimin/search-yugioh-card

permalink: /:title.rb
files: "/search-yugioh-card"
